In [41]:
Challange_filename = 'C:/Users/52353/MUVA_RP_2020-master/Datasets/vehiculos_reto2.csv'
Test_filename ='C:/Users/52353/MUVA_RP_2020-master/Datasets/vehiculos_reto2.csv'

In [42]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt



In [43]:
FullSet = pd.read_csv(Challange_filename)
FullSet.head()

COMPACTNESS  CIRCULARITY  DISTANCE_CIRCULARITY  RADIUS_RATIO  \
0           93           39                    63           146   
1           91           42                    84           209   
2           94           48                    83           162   
3           90           44                    72           157   
4          105           54                   108           234   

   PR.AXIS_ASPECT_RATIO  MAX.LENGTH_ASPECT_RATIO  SCATTER_RATIO  \
0                    58                        7            128   
1                    75                        6            171   
2                    64                       10            156   
3                    64                        8            137   
4                    70                       12            215   

   ELONGATEDNESS  PR.AXIS_RECTANGULARITY  MAX.LENGTH_RECTANGULARITY  \
0             52                      18                        134   
1             38                      20                        138   
2             43                      19                        153   
3             48                      18                        144   
4             31                      24                        168   

   SCALED_VARIANCE_MAJOR  SCALED_VARIANCE_MINOR  SCALED_RADIUS_OF_GYRATION  \
0                    149                    246                        158   
1                    189                    446                        161   
2                    177                    357                        187   
3                    159                    283                        171   
4                    226                    687                        228   

   SKEWNESS_ABOUT_MAJOR  SKEWNESS_ABOUT_MINOR  KURTOSIS_ABOUT_MAJOR  \
0                    63                     9                     7   
1                    69                     3                    12   
2                    74                     4                    14   
3                    65                     9                     4   
4                    68                     4                    22   

   KURTOSIS_ABOUT_MINOR  HOLLOWS_RATIO Class  
0                   198            204  saab  
1                   196            201   bus  
2                   185            196   van  
3                   196            203   van  
4                   189            201  saab

In [44]:
FullSet.head()

COMPACTNESS  CIRCULARITY  DISTANCE_CIRCULARITY  RADIUS_RATIO  \
0           93           39                    63           146   
1           91           42                    84           209   
2           94           48                    83           162   
3           90           44                    72           157   
4          105           54                   108           234   

   PR.AXIS_ASPECT_RATIO  MAX.LENGTH_ASPECT_RATIO  SCATTER_RATIO  \
0                    58                        7            128   
1                    75                        6            171   
2                    64                       10            156   
3                    64                        8            137   
4                    70                       12            215   

   ELONGATEDNESS  PR.AXIS_RECTANGULARITY  MAX.LENGTH_RECTANGULARITY  \
0             52                      18                        134   
1             38                      20                        138   
2             43                      19                        153   
3             48                      18                        144   
4             31                      24                        168   

   SCALED_VARIANCE_MAJOR  SCALED_VARIANCE_MINOR  SCALED_RADIUS_OF_GYRATION  \
0                    149                    246                        158   
1                    189                    446                        161   
2                    177                    357                        187   
3                    159                    283                        171   
4                    226                    687                        228   

   SKEWNESS_ABOUT_MAJOR  SKEWNESS_ABOUT_MINOR  KURTOSIS_ABOUT_MAJOR  \
0                    63                     9                     7   
1                    69                     3                    12   
2                    74                     4                    14   
3                    65                     9                     4   
4                    68                     4                    22   

   KURTOSIS_ABOUT_MINOR  HOLLOWS_RATIO Class  
0                   198            204  saab  
1                   196            201   bus  
2                   185            196   van  
3                   196            203   van  
4                   189            201  saab

In [45]:
FullX = FullSet.drop('Class', axis=1)
FullX.head()

COMPACTNESS  CIRCULARITY  DISTANCE_CIRCULARITY  RADIUS_RATIO  \
0           93           39                    63           146   
1           91           42                    84           209   
2           94           48                    83           162   
3           90           44                    72           157   
4          105           54                   108           234   

   PR.AXIS_ASPECT_RATIO  MAX.LENGTH_ASPECT_RATIO  SCATTER_RATIO  \
0                    58                        7            128   
1                    75                        6            171   
2                    64                       10            156   
3                    64                        8            137   
4                    70                       12            215   

   ELONGATEDNESS  PR.AXIS_RECTANGULARITY  MAX.LENGTH_RECTANGULARITY  \
0             52                      18                        134   
1             38                      20                        138   
2             43                      19                        153   
3             48                      18                        144   
4             31                      24                        168   

   SCALED_VARIANCE_MAJOR  SCALED_VARIANCE_MINOR  SCALED_RADIUS_OF_GYRATION  \
0                    149                    246                        158   
1                    189                    446                        161   
2                    177                    357                        187   
3                    159                    283                        171   
4                    226                    687                        228   

   SKEWNESS_ABOUT_MAJOR  SKEWNESS_ABOUT_MINOR  KURTOSIS_ABOUT_MAJOR  \
0                    63                     9                     7   
1                    69                     3                    12   
2                    74                     4                    14   
3                    65                     9                     4   
4                    68                     4                    22   

   KURTOSIS_ABOUT_MINOR  HOLLOWS_RATIO  
0                   198            204  
1                   196            201  
2                   185            196  
3                   196            203  
4                   189            201

In [46]:
FullY=FullSet[['Class']]
print(FullY['Class'].unique())

['saab' 'bus' 'van' 'opel']


In [47]:
nombres=['Hao Zeng']

In [48]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 100))
X = scaler.fit_transform(FullX)
Y = FullY.values.ravel()

In [49]:
X

array([[43.47826087, 23.07692308, 32.85714286, ..., 17.5       ,
        78.57142857, 76.66666667],
       [39.13043478, 34.61538462, 62.85714286, ..., 30.        ,
        71.42857143, 66.66666667],
       [45.65217391, 57.69230769, 61.42857143, ..., 35.        ,
        32.14285714, 50.        ],
       ...,
       [54.34782609, 34.61538462, 71.42857143, ..., 20.        ,
        82.14285714, 90.        ],
       [58.69565217, 46.15384615, 85.71428571, ..., 12.5       ,
        46.42857143, 46.66666667],
       [19.56521739, 38.46153846, 44.28571429, ..., 27.5       ,
        17.85714286, 16.66666667]])

In [50]:
from sklearn.ensemble import RandomForestClassifier  
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold,cross_val_score
clf = RandomForestClassifier()
cross_val_score(clf,X,Y,cv=10)
clf.fit(X,Y)

RandomForestClassifier()

In [51]:
FullSet = pd.read_csv(Test_filename, header=0)
TestX_ = FullSet.drop('Class', axis=1)
TestY_ = FullSet[['Class']]
X_test = scaler.transform(TestX_)
Y_test = TestY_.values.ravel() 

In [52]:
from sklearn.metrics import confusion_matrix

Y_hat = clf.predict(X_test)
conf_mat = confusion_matrix(Y_test , Y_hat)
N_success  = np.trace(conf_mat)
N_fails = Y_test.shape[0]-N_success
#-------------------------------
print (nombres,"\n")
print("Confusion matrix:\n")
print(conf_mat,"\n")
print("Outcome:\n")
strlog = "  :) HIT  = %d, (%0.2f%%)"%(N_success, 100*N_success/(N_success+N_fails))
print(strlog)
strlog = "  :( FAIL = %d, (%0.2f%%)"%(N_fails, 100*N_fails/(N_success+N_fails))
print(strlog)

['Hao Zeng'] 

Confusion matrix:

[[153   0   0   0]
 [  0 148   0   0]
 [  0   0 152   0]
 [  0   0   0 139]] 

Outcome:

  :) HIT  = 592, (100.00%)
  :( FAIL = 0, (0.00%)
